# Generated by Django 6.1.1 on 2026-09-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
